version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_app
    ports:
      - "80:80" # Maps port 80 on the host to port 80 on the container
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
